//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiwiBike4Rent
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIKE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BIKE()
        {
            this.RENTALs = new HashSet<RENTAL>();
        }
    
        public int BikeID { get; set; }
        public int Model { get; set; }
        public int RentalPrice { get; set; }
        public string Status { get; set; }
        public int LifeTime { get; set; }
        public System.DateTime ManufacturedYear { get; set; }
        public string Accessories { get; set; }
        public Nullable<System.DateTime> rentedDate { get; set; }
        public Nullable<System.DateTime> dueBackDate { get; set; }
    
        public virtual MODEL MODEL1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RENTAL> RENTALs { get; set; }
    }
}
