//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiwiBike4Rent
{
    using System;
    using System.Collections.Generic;
    
    public partial class RENTAL
    {
        public int RentalID { get; set; }
        public int CustomerID { get; set; }
        public int BikeID { get; set; }
        public int Deposit { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
    
        public virtual BIKE BIKE { get; set; }
        public virtual CUSTOMER CUSTOMER { get; set; }
    }
}
