//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiwiBike4Rent
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAFF
    {
        public int StaffID { get; set; }
        public string Name { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Address { get; set; }
        public string Tel { get; set; }
        public string OfficeAddress { get; set; }
        public string ExtNumber { get; set; }
        public string UserType { get; set; }
        public string Role { get; set; }
    }
}
